export interface StyleConfig {
  name: string
  desc: string
  prompt: string
  keywords: string
  bg: string
  text: string
  card: string
  button: string
  buttonSec: string
  input: string
  highlight: string
  badge: string
  font: string
}

export const styles = {
  // ==========================================
  // 1. 原始風格 (Original 17 Styles)
  // ==========================================
  arc: {
    name: "Arc Browser",
    desc: "磨砂玻璃、無邊框、流動感",
    prompt: "Design a modern web interface with a glassmorphism aesthetic inspired by Arc Browser. Use translucent backgrounds with soft rose-to-indigo gradients, borderless containers, and a blurred overlay effect. The UI should feel fluid and organic with rounded corners and clean sans-serif typography.",
    keywords: "glassmorphism, translucent, borderless, soft gradients, blur overlay",
    bg: "bg-gradient-to-br from-rose-100 via-sky-100 to-indigo-100",
    text: "text-slate-800",
    card: "bg-white/40 backdrop-blur-xl border-none shadow-sm rounded-2xl",
    button: "bg-white/50 hover:bg-white/80 text-slate-900 shadow-sm backdrop-blur-md rounded-xl border border-white/20",
    buttonSec: "bg-transparent hover:bg-white/30 text-slate-700",
    input: "bg-white/30 border-none rounded-xl focus:ring-2 focus:ring-indigo-300 placeholder-slate-500",
    highlight: "text-indigo-600",
    badge: "bg-indigo-100/50 text-indigo-700 rounded-lg",
    font: "font-sans",
  },
  tremor: {
    name: "Tremor",
    desc: "數據儀表板、乾淨卡片、專業圖表",
    prompt: "Create a clean analytical dashboard UI inspired by Tremor. Use a stark white background for cards with subtle ring borders, slate gray text, and professional blue accents. Focus on data visualization clarity, high readability, and a structured layout.",
    keywords: "dashboard UI, analytical, clean stats, white cards, subtle ring",
    bg: "bg-slate-50",
    text: "text-slate-900",
    card: "bg-white shadow-sm ring-1 ring-slate-200 rounded-lg",
    button: "bg-blue-500 hover:bg-blue-600 text-white shadow-sm rounded-md font-medium",
    buttonSec: "bg-white border border-slate-300 text-slate-700 hover:bg-slate-50",
    input: "bg-white border border-slate-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500",
    highlight: "text-blue-600",
    badge: "bg-blue-50 text-blue-700 rounded-md ring-1 ring-inset ring-blue-700/10",
    font: "font-sans",
  },
  neobrutalism: {
    name: "Neobrutalism (Gumroad)",
    desc: "粗黑框、高對比色、大膽陰影",
    prompt: "Generate a neo-brutalism style UI inspired by Gumroad. Use high contrast colors like bright yellow background, thick 2px-4px black borders, hard non-blurred shadows, and bold typography. Elements should have a raw, unpolished look with sharp edges and vibrant accents.",
    keywords: "neo-brutalism, high contrast, thick black borders, hard shadows, vibrant colors",
    bg: "bg-[#FFDE59]",
    text: "text-black",
    card: "bg-white border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] rounded-none",
    button: "bg-[#FF6B6B] hover:bg-[#ff5252] text-black border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] transition-all font-bold rounded-none",
    buttonSec: "bg-white text-black border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]",
    input: "bg-white border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] focus:outline-none focus:bg-pink-50 rounded-none",
    highlight: "text-black bg-[#4ADE80] px-1 border-2 border-black",
    badge: "bg-[#A78BFA] text-black border-2 border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] font-bold rounded-none",
    font: "font-mono",
  },
  supabase: {
    name: "Supabase",
    desc: "深色模式、翠綠色調、開發者工具",
    prompt: "Design a dark mode developer tool interface similar to Supabase. Use a deep dark gray background, emerald green accents (#3ECF8E), flat design, and clean 1px borders. Focus on high readability for code and data with a technical, modern feel.",
    keywords: "dark mode, developer tool, emerald accent, flat design, clean dark",
    bg: "bg-[#1C1C1C]",
    text: "text-[#EDEDED]",
    card: "bg-[#232323] border border-[#2E2E2E] rounded-md",
    button: "bg-[#3ECF8E] hover:bg-[#34b27b] text-[#151515] rounded-md font-medium",
    buttonSec: "bg-[#2E2E2E] hover:bg-[#383838] text-white border border-[#3E3E3E]",
    input: "bg-[#1C1C1C] border border-[#3E3E3E] text-white focus:border-[#3ECF8E] focus:ring-0 rounded-md",
    highlight: "text-[#3ECF8E]",
    badge: "bg-[#3ECF8E]/10 text-[#3ECF8E] border border-[#3ECF8E]/20 rounded-full",
    font: "font-sans",
  },
  grafana: {
    name: "Grafana",
    desc: "監控儀表板、黑色背景、霓虹線條",
    prompt: "Create a monitoring dashboard UI inspired by Grafana. Use a deep black background, high contrast neon orange and green accents, and sharp borders. The design should feel technical, data-heavy, and suitable for real-time visualization.",
    keywords: "monitoring dashboard, dark theme, neon accents, data heavy, high contrast",
    bg: "bg-[#0B0C0E]",
    text: "text-[#DCDCDC]",
    card: "bg-[#181B1F] border-t-2 border-orange-500 rounded-sm shadow-md",
    button: "bg-gradient-to-b from-orange-500 to-orange-600 text-white rounded-[2px] font-semibold border border-orange-400",
    buttonSec: "bg-[#22252B] text-gray-300 border border-[#333] hover:text-white",
    input: "bg-[#0B0C0E] border border-[#2C3235] text-white focus:border-orange-500 rounded-[2px]",
    highlight: "text-orange-500",
    badge: "bg-[#232529] text-[#56A64B] border border-[#56A64B]/30 rounded-full",
    font: "font-sans",
  },
  cupertino: {
    name: "Cupertino (iOS)",
    desc: "蘋果風格、半透明、大標題、圓潤",
    prompt: "Design an iOS-style interface (Cupertino). Use a light gray system background, white cards with large rounded corners (20px+), translucent blur effects, and San Francisco-style typography with large headers and blue active states.",
    keywords: "iOS style, rounded corners, blur, system gray, sf pro, clean",
    bg: "bg-[#F2F2F7]",
    text: "text-black",
    card: "bg-white rounded-[20px] shadow-sm",
    button: "bg-[#007AFF] hover:bg-[#0063cf] text-white rounded-full font-semibold px-6",
    buttonSec: "bg-[#E5E5EA] text-[#007AFF] hover:bg-[#d1d1d6] rounded-full",
    input: "bg-[#E5E5EA] border-none text-black placeholder-gray-500 focus:ring-0 rounded-xl px-4",
    highlight: "text-[#007AFF]",
    badge: "bg-gray-100 text-gray-600 rounded-md",
    font: "font-sans tracking-tight",
  },
  material3: {
    name: "Material Design 3",
    desc: "Google 風格、膠囊按鈕、動態色",
    prompt: "Create a Material Design 3 (Material You) interface. Use dynamic pastel colors, pill-shaped buttons, rounded cards with elevation, and a playful yet accessible layout. Backgrounds should be light and airy with purple tones.",
    keywords: "material you, dynamic color, playful, rounded, pastel tones",
    bg: "bg-[#FEF7FF]",
    text: "text-[#1D1B20]",
    card: "bg-[#F3EDF7] rounded-[24px] shadow-none hover:shadow-md transition-shadow",
    button: "bg-[#6750A4] text-white rounded-full font-medium hover:shadow-md transition-shadow",
    buttonSec: "bg-transparent text-[#6750A4] border border-[#79747E] rounded-full hover:bg-[#E8DEF8]",
    input: "bg-[#E7E0EC] border-b-2 border-[#49454F] rounded-t-lg rounded-b-none focus:border-[#6750A4] bg-opacity-50",
    highlight: "text-[#6750A4]",
    badge: "bg-[#E8DEF8] text-[#1D1B20] rounded-lg",
    font: "font-sans",
  },
  notion: {
    name: "Notion",
    desc: "文件感、Emoji、簡潔灰底",
    prompt: "Design a productivity tool interface inspired by Notion. Use a stark white background, serif or clean sans-serif typography, minimal icons, and light gray hover states. Keep it extremely clean, spacious, and document-focused.",
    keywords: "sober, productivity tool, clean slate, typography focused, minimal icons",
    bg: "bg-white",
    text: "text-[#37352F]",
    card: "bg-white hover:bg-[#F7F7F5] transition-colors border border-[#E9E9E7] rounded-sm",
    button: "bg-[#2383E2] hover:bg-[#1d6fbf] text-white rounded-[3px] font-normal text-sm shadow-sm",
    buttonSec: "bg-transparent hover:bg-[#EFEFED] text-[#37352F] border border-[#D9D9D7] rounded-[3px] text-sm",
    input: "bg-[#F7F7F5] border border-transparent focus:border-[#2383E2] focus:bg-white rounded-[3px] text-sm",
    highlight: "bg-[#FDECC8] text-[#37352F]",
    badge: "bg-[#E3E2E0] text-[#37352F] rounded-[3px] px-1",
    font: "font-sans",
  },
  salesforce: {
    name: "Salesforce Lightning",
    desc: "企業 CRM、高資訊密度、緊湊",
    prompt: "Create an enterprise CRM interface similar to Salesforce Lightning. Use a dense information layout, distinct blue-grey background, white cards with subtle shadows, and compact spacing. Focus on utility, density, and professional blue accents.",
    keywords: "enterprise UI, information density, blue accents, compact, professional",
    bg: "bg-[#B0C4DF]",
    text: "text-[#080707]",
    card: "bg-white border border-[#DDDBDA] rounded-[4px] shadow-sm",
    button: "bg-[#0176D3] hover:bg-[#014486] text-white rounded-[4px] font-normal text-[13px]",
    buttonSec: "bg-white text-[#0176D3] border border-[#DDDBDA] hover:bg-[#F3F2F2] rounded-[4px] text-[13px]",
    input: "bg-white border border-[#DDDBDA] rounded-[4px] focus:ring-1 focus:ring-[#0176D3] focus:border-[#0176D3]",
    highlight: "text-[#0176D3]",
    badge: "bg-[#ECEBEA] text-[#080707] rounded-[4px] uppercase text-[10px] tracking-wide font-bold",
    font: "font-sans",
  },
  win95: {
    name: "Windows 95",
    desc: "復古像素、立體按鈕、水泥灰",
    prompt: "Generate a retro Windows 95 style UI. Use a teal desktop background, gray beveled buttons and windows (pixel art style), black pixel fonts, and high contrast borders (white/black) to simulate 3D depth and relief.",
    keywords: "retro, pixel art, bevel, gray background, classic windows, brutalist structure",
    bg: "bg-[#008080]",
    text: "text-black",
    card: "bg-[#C0C0C0] border-t-2 border-l-2 border-b-2 border-r-2 border-t-white border-l-white border-b-black border-r-black p-1",
    button: "bg-[#C0C0C0] active:border-t-black active:border-l-black active:border-b-white active:border-r-white border-t-2 border-l-2 border-b-2 border-r-2 border-t-white border-l-white border-b-black border-r-black text-black font-bold active:translate-y-[1px]",
    buttonSec: "bg-[#C0C0C0] border-t-2 border-l-2 border-b-2 border-r-2 border-t-white border-l-white border-b-black border-r-black text-black",
    input: "bg-white border-t-2 border-l-2 border-b-2 border-r-2 border-t-black border-l-black border-b-white border-r-white rounded-none focus:outline-none focus:bg-blue-800 focus:text-white",
    highlight: "bg-blue-800 text-white px-1",
    badge: "bg-[#C0C0C0] border border-black px-1 text-black text-xs",
    font: "font-mono",
  },
  vercel: {
    name: "Vercel / Geist",
    desc: "極簡黑白、幾何感、Next.js 美學",
    prompt: "Design a minimalist, geometric interface inspired by Vercel/Geist. Use a monochrome black and white palette, sharp edges, subtle borders, and a focus on typography and white space. Ensure a technical and high-performance look.",
    keywords: "minimalist, monochrome, geometric, technical, sharp",
    bg: "bg-black",
    text: "text-white",
    card: "bg-black border border-[#333] rounded-lg hover:border-white transition-colors duration-300",
    button: "bg-white hover:bg-gray-200 text-black rounded-md font-medium text-sm h-10 px-4",
    buttonSec: "bg-black hover:bg-[#111] text-[#888] hover:text-white border border-[#333] rounded-md text-sm",
    input: "bg-black border border-[#333] text-white rounded-md focus:border-white focus:ring-1 focus:ring-white placeholder-[#444]",
    highlight: "text-white font-bold",
    badge: "bg-[#111] text-[#666] border border-[#333] rounded-full px-3",
    font: "font-sans tracking-tight",
  },
  linear: {
    name: "Linear",
    desc: "暗黑模式聖經、紫色漸層、極致邊框",
    prompt: "Create a luxury dark mode interface inspired by Linear. Use a deep dark background (#0B0C0E), subtle purple gradients and glows, ultra-thin borders, and high precision typography. It should feel fast, premium, and finely crafted.",
    keywords: "luxury dark mode, glows, subtle gradients, precision, purple accents",
    bg: "bg-[#0B0C0E]",
    text: "text-[#E0E1E6]",
    card: "bg-[#141519] border border-white/5 rounded-lg shadow-2xl hover:border-white/10 transition-colors",
    button: "bg-gradient-to-b from-[#6E66FA] to-[#5E56E8] shadow-[0px_0px_12px_rgba(94,86,232,0.4)] hover:shadow-[0px_0px_16px_rgba(94,86,232,0.6)] text-white rounded-md font-medium text-sm border border-white/10",
    buttonSec: "bg-[#1C1D21] hover:bg-[#232429] text-[#D0D2D6] border border-white/5 rounded-md text-sm",
    input: "bg-[#0B0C0E] border border-white/10 text-white rounded-md focus:border-[#5E56E8] placeholder-white/20",
    highlight: "text-[#5E56E8]",
    badge: "bg-[#5E56E8]/10 text-[#7C75F2] border border-[#5E56E8]/20 rounded-md",
    font: "font-sans",
  },
  shadcn: {
    name: "Shadcn/ui",
    desc: "乾淨 Slate 灰階、現代 React 標竿",
    prompt: "Design a modern, clean web app interface using Shadcn/ui principles. Use a slate gray scale, consistent rounded corners, clean 1px borders, and a focus on accessibility and reusability. Simple, elegant, and standard.",
    keywords: "clean, reusable components, slate gray, accessibility, modern standard",
    bg: "bg-white",
    text: "text-slate-950",
    card: "bg-white border border-slate-200 rounded-xl shadow-sm text-slate-950",
    button: "bg-slate-900 hover:bg-slate-900/90 text-slate-50 rounded-md font-medium text-sm",
    buttonSec: "bg-white hover:bg-slate-100 text-slate-900 border border-slate-200 rounded-md text-sm",
    input: "bg-transparent border border-slate-200 rounded-md text-sm ring-offset-white placeholder:text-slate-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-950 focus-visible:ring-offset-2",
    highlight: "text-slate-900 underline decoration-slate-400 decoration-2 underline-offset-4",
    badge: "bg-slate-100 text-slate-900 hover:bg-slate-100/80 rounded-full border border-slate-200 font-semibold text-xs",
    font: "font-sans",
  },
  carbon: {
    name: "IBM Carbon",
    desc: "工業風、網格系統、精確度",
    prompt: "Create an industrial interface inspired by IBM Carbon Design System. Use a dark gray theme, strict grid alignment, rectangular touch targets, and high precision. Focus on functionality and structure over decoration.",
    keywords: "industrial, grid based, precision, enterprise, functional",
    bg: "bg-[#161616]",
    text: "text-[#F4F4F4]",
    card: "bg-[#262626] border-none rounded-none p-4",
    button: "bg-[#0F62FE] hover:bg-[#0353E9] text-white rounded-none font-normal text-sm flex justify-between items-center pr-4",
    buttonSec: "bg-[#393939] hover:bg-[#4C4C4C] text-white rounded-none",
    input: "bg-[#262626] border-b border-[#8D8D8D] text-white rounded-none focus:outline-none focus:ring-2 focus:ring-[#0F62FE] placeholder-[#525252]",
    highlight: "text-[#0F62FE]",
    badge: "bg-[#393939] text-[#A8A8A8] rounded-full text-xs font-mono",
    font: "font-sans",
  },
  ant: {
    name: "Ant Design Pro",
    desc: "亞洲企業後台霸主、阿里雲藍",
    prompt: "Design an enterprise back-office interface inspired by Ant Design Pro. Use a light gray background, clean white cards, reliable blue primary buttons, and a dense, data-rich layout suitable for complex tables and management systems.",
    keywords: "enterprise, complex data, reliable, blue theme, dense",
    bg: "bg-[#F0F2F5]",
    text: "text-[rgba(0,0,0,0.85)]",
    card: "bg-white border border-[#F0F0F0] rounded-[2px] shadow-sm",
    button: "bg-[#1890FF] hover:bg-[#40A9FF] text-white rounded-[2px] shadow-[0_2px_0_rgba(0,0,0,0.045)] text-sm",
    buttonSec: "bg-white hover:text-[#40A9FF] hover:border-[#40A9FF] text-[rgba(0,0,0,0.85)] border border-[#D9D9D9] rounded-[2px] text-sm",
    input: "bg-white border border-[#D9D9D9] hover:border-[#40A9FF] focus:border-[#40A9FF] focus:ring-2 focus:ring-[#1890ff]/20 rounded-[2px]",
    highlight: "text-[#1890FF]",
    badge: "bg-[#E6F7FF] text-[#1890FF] border border-[#91D5FF] rounded-[2px]",
    font: "font-sans",
  },
  metronic: {
    name: "Metronic",
    desc: "萬能模板王、豐富的元件堆疊",
    prompt: "Create a feature-rich admin dashboard inspired by Metronic. Use a dark navy background, vibrant blue and yellow accents, gradients, and a wide variety of UI components. The style should feel like a premium, comprehensive Bootstrap theme.",
    keywords: "bootstrap theme, heavy ui, feature rich, gradients, dashboard king",
    bg: "bg-[#151521]",
    text: "text-[#FFFFFF]",
    card: "bg-[#1E1E2D] rounded-[0.475rem] shadow-none",
    button: "bg-[#009EF7] hover:bg-[#0095E8] text-white rounded-[0.475rem] font-semibold text-sm",
    buttonSec: "bg-[#2B2B40] hover:bg-[#323248] text-[#CDCDDE] rounded-[0.475rem] font-medium text-sm",
    input: "bg-[#151521] border border-transparent text-[#92929F] focus:border-[#009EF7] focus:bg-[#151521] rounded-[0.475rem] font-medium text-xs",
    highlight: "text-[#009EF7]",
    badge: "bg-[#392F28] text-[#FFC700] rounded-[0.475rem] font-bold text-xs",
    font: "font-sans",
  },
  adminlte: {
    name: "AdminLTE",
    desc: "經典 Bootstrap 4、卡片式管理介面",
    prompt: "Design a classic Bootstrap 4 admin panel inspired by AdminLTE. Use a card-based layout with top colored borders (blue/success), standard buttons, and a structured layout. The look should be dependable, legacy-compatible, and functional.",
    keywords: "bootstrap 4, classic admin, card interface, dependable, legacy modern",
    bg: "bg-[#F4F6F9]",
    text: "text-[#212529]",
    card: "bg-white border-t-[3px] border-t-[#007bff] rounded-[0.25rem] shadow-[0_0_1px_rgba(0,0,0,.125),0_1px_3px_rgba(0,0,0,.2)]",
    button: "bg-[#007BFF] hover:bg-[#0069d9] text-white rounded-[0.2rem] shadow-none font-normal",
    buttonSec: "bg-[#6C757D] hover:bg-[#5a6268] text-white rounded-[0.2rem]",
    input: "bg-white border border-[#ced4da] rounded-[0.2rem] focus:border-[#80bdff] focus:ring-[0.2rem] focus:ring-[rgba(0,123,255,.25)] text-[#495057]",
    highlight: "text-[#28a745]",
    badge: "bg-[#17a2b8] text-white rounded-[0.25rem] font-bold text-[75%]",
    font: "font-sans",
  },

  // ==========================================
  // 2. 電影與電玩主題風格 (New 10 Styles)
  // ==========================================

  matrix: {
    name: "Matrix (駭客任務)",
    desc: "終端機綠、黑色背景、代碼雨氛圍",
    prompt: "Design a Matrix-inspired digital interface. Use a pitch black background with vibrant terminal green text (#00FF41). Elements should resemble command-line inputs, raw code blocks, and retro-futuristic hacker terminals. Use monospaced fonts and glowing green borders.",
    keywords: "matrix, hacker, terminal green, black background, digital rain, monospace",
    bg: "bg-black",
    text: "text-[#22c55e]",
    card: "bg-[#0a0a0a] border border-[#22c55e]/50 shadow-[0_0_10px_rgba(34,197,94,0.1)] rounded-sm",
    button: "bg-[#14532d] hover:bg-[#22c55e] hover:text-black text-[#22c55e] border border-[#22c55e] rounded-none font-mono tracking-widest uppercase transition-all duration-300 hover:shadow-[0_0_15px_rgba(34,197,94,0.6)]",
    buttonSec: "bg-black text-[#22c55e] border border-[#22c55e]/50 hover:border-[#22c55e] rounded-none font-mono",
    input: "bg-black border border-[#22c55e] text-[#22c55e] focus:shadow-[0_0_10px_rgba(34,197,94,0.4)] rounded-none font-mono placeholder-[#14532d]",
    highlight: "text-[#4ade80] shadow-[0_0_5px_rgba(34,197,94,0.8)]",
    badge: "bg-[#052e16] text-[#4ade80] border border-[#22c55e] rounded-none font-mono text-xs",
    font: "font-mono",
  },

  acnh: {
    name: "Animal Crossing (動森)",
    desc: "柔和米綠色、圓潤卡片、療癒手寫感",
    prompt: "Create a cozy, playful interface inspired by Animal Crossing: New Horizons. Use a creamy off-white or soft pastel green background, extremely rounded white cards (bubbles), and soft teal/leaf green buttons. The typography should be friendly and rounded.",
    keywords: "animal crossing, cozy, pastel green, rounded, playful, soft UI",
    bg: "bg-[#F0F5E1]",
    text: "text-[#7A725D]",
    card: "bg-white rounded-[2rem] shadow-[4px_4px_0px_rgba(0,0,0,0.05)] border-2 border-[#E9E4D0]",
    button: "bg-[#7ED3C7] hover:bg-[#6BC2B6] text-white rounded-full font-bold tracking-wide shadow-[2px_2px_0px_rgba(0,0,0,0.1)] border-2 border-white",
    buttonSec: "bg-[#FDFBF6] text-[#7A725D] hover:bg-[#FFF] rounded-full font-bold border-2 border-[#E8E1CD]",
    input: "bg-[#FDFBF6] border-2 border-[#E8E1CD] rounded-full text-[#7A725D] focus:border-[#7ED3C7] focus:ring-2 focus:ring-[#7ED3C7]/20 px-6",
    highlight: "text-[#7ED3C7]",
    badge: "bg-[#FFEFD5] text-[#D4A373] rounded-full border border-[#FFE4C4] font-bold px-3",
    font: "font-sans",
  },

  mario: {
    name: "Super Mario (馬力歐)",
    desc: "鮮豔紅藍黃、高飽和度、充滿活力",
    prompt: "Design a cheerful, vibrant interface inspired by Super Mario. Use iconic Mario Red (#E52521) and Overworld Blue (#6B8CFF) with bright Yellow accents. Elements should be chunky, rounded, and glossy, evoking the feel of Mario UI blocks and buttons.",
    keywords: "super mario, vibrant red, playful, chunky buttons, nintendo style",
    bg: "bg-[#6B8CFF]",
    text: "text-[#1C1C1C]",
    card: "bg-[#F8F9FA] rounded-2xl shadow-[0_6px_0_rgba(0,0,0,0.2)] border-4 border-white",
    button: "bg-[#E52521] hover:bg-[#D41F1C] text-white rounded-xl font-black uppercase tracking-wide border-b-[6px] border-[#9E0E0B] active:border-b-0 active:translate-y-[6px] transition-all",
    buttonSec: "bg-[#FBD000] hover:bg-[#E5BE00] text-[#5C4500] rounded-xl font-black border-b-[6px] border-[#B89800] active:border-b-0 active:translate-y-[6px] transition-all",
    input: "bg-white border-4 border-[#E52521] rounded-xl focus:ring-4 focus:ring-[#FBD000] text-black font-bold",
    highlight: "text-[#E52521]",
    badge: "bg-[#E52521] text-white border-2 border-white rounded-full font-black shadow-md",
    font: "font-sans",
  },

  cyberpunk: {
    name: "Cyberpunk 2077",
    desc: "賽博黃、故障藝術、稜角分明",
    prompt: "Create a futuristic, dystopian interface inspired by Cyberpunk 2077. Use the signature 'Cyber Yellow' (#FCEE0A) against a dark gritty background. Shapes should be angular with cut corners, glitch effects, and technical decorative lines.",
    keywords: "cyberpunk, glitch, cyber yellow, angular, futuristic, dystopian",
    bg: "bg-[#050505]",
    text: "text-[#FCEE0A]",
    card: "bg-[#111] border border-[#FCEE0A]/40 rounded-none clip-path-slant shadow-[4px_4px_0_#000]",
    button: "bg-[#00F0FF] hover:bg-[#FFFFFF] text-black font-bold uppercase tracking-widest rounded-none border-none hover:shadow-[0_0_15px_#00F0FF] transition-all clip-path-slant",
    buttonSec: "bg-transparent text-[#FCEE0A] border border-[#FCEE0A] hover:bg-[#FCEE0A] hover:text-black rounded-none uppercase font-bold",
    input: "bg-[#1a1a1a] border-l-4 border-l-[#FCEE0A] border-y border-r border-[#333] text-[#FCEE0A] focus:bg-[#222] rounded-none font-mono",
    highlight: "text-[#00F0FF]",
    badge: "bg-[#290000] text-[#FF5E5E] border border-[#FF5E5E] rounded-none font-mono uppercase text-xs px-2",
    font: "font-sans",
  },

  minecraft: {
    name: "Minecraft (麥塊)",
    desc: "像素風格、方塊感、石頭材質灰",
    prompt: "Design a voxel-inspired interface based on Minecraft. Use pixelated fonts, stone-gray backgrounds with bevel effects (light top/left, dark bottom/right borders), and earthy tones. The UI should feel like a game inventory screen.",
    keywords: "minecraft, pixel art, voxel, stone gray, bevel border, retro game",
    bg: "bg-[#121212]",
    text: "text-[#E0E0E0]",
    card: "bg-[#C6C6C6] border-[4px] border-t-white border-l-white border-b-[#555] border-r-[#555] text-black shadow-lg",
    button: "bg-[#7E7E7E] text-white border-[2px] border-black hover:bg-[#8E8E8E] active:bg-[#6E6E6E] font-mono shadow-[inset_2px_2px_0_rgba(255,255,255,0.2),inset_-2px_-2px_0_rgba(0,0,0,0.4)] rounded-none",
    buttonSec: "bg-[#C6C6C6] text-black border-[2px] border-black hover:bg-[#D6D6D6] font-mono",
    input: "bg-black border-[2px] border-[#555] text-white p-2 font-mono rounded-none focus:border-white",
    highlight: "text-[#55FF55] drop-shadow-[2px_2px_0_rgba(0,0,0,1)]",
    badge: "bg-[#3A0B55] text-[#D276FF] border-2 border-black font-mono text-xs",
    font: "font-mono",
  },

  fallout: {
    name: "Fallout (Pip-Boy)",
    desc: "嗶嗶小子綠、掃描線、復古未來",
    prompt: "Create a retro-futuristic interface inspired by the Fallout Pip-Boy. Use a monochromatic phosphor green color scheme on a black background. Include scanline effects, CRT aesthetic, and retro technical typography.",
    keywords: "fallout, pip-boy, cathode green, retro futuristic, monochrome, crt",
    bg: "bg-[#0F120F]",
    text: "text-[#16F529]",
    card: "bg-[#0A100A] border border-[#16F529] shadow-[0_0_8px_rgba(22,245,41,0.2)] rounded-lg relative overflow-hidden",
    button: "bg-[#16F529]/10 hover:bg-[#16F529] hover:text-black text-[#16F529] border border-[#16F529] rounded-sm font-bold tracking-wider uppercase transition-colors",
    buttonSec: "bg-transparent text-[#16F529] border border-[#16F529]/50 hover:border-[#16F529] rounded-sm opacity-80",
    input: "bg-[#050805] border border-[#16F529] text-[#16F529] focus:shadow-[0_0_10px_rgba(22,245,41,0.4)] rounded-sm font-mono placeholder-[#16F529]/30",
    highlight: "text-[#16F529] font-bold underline decoration-2 underline-offset-4",
    badge: "bg-[#16F529]/20 text-[#16F529] border border-[#16F529] rounded-sm font-mono text-xs",
    font: "font-mono",
  },

  persona: {
    name: "Persona 5 (女神異聞錄)",
    desc: "龐克紅黑、剪貼風格、銳利角度",
    prompt: "Design a stylish, rebellious interface inspired by Persona 5. Use a bold red (#D91818), black, and white color scheme. Elements should be irregularly shaped, rotated, or resemble comic book cutouts. Typography should be bold and dynamic.",
    keywords: "persona 5, phantom thieves, bold red, comic style, rotated, stylish",
    bg: "bg-[#1a1a1a]",
    text: "text-white",
    card: "bg-black text-white -rotate-1 border-2 border-black shadow-[4px_4px_0_#D91818] rounded-sm",
    button: "bg-[#D91818] text-white font-black uppercase italic tracking-tighter -skew-x-12 hover:bg-black hover:text-[#D91818] border-2 border-transparent hover:border-[#D91818] transition-all transform hover:-translate-y-1 shadow-lg",
    buttonSec: "bg-white text-black font-bold uppercase italic -skew-x-12 border-2 border-black hover:bg-black hover:text-white",
    input: "bg-white border-b-4 border-black text-black font-bold italic focus:border-[#D91818] focus:bg-black focus:text-white transition-colors rounded-none px-2",
    highlight: "bg-black text-white px-1 -skew-x-6 inline-block",
    badge: "bg-[#D91818] text-white -rotate-3 border-2 border-white shadow-md font-bold px-2",
    font: "font-sans",
  },

  gta: {
    name: "GTA: Vice City (懷舊)",
    desc: "80年代霓虹、粉紅與青色、邁阿密風",
    prompt: "Create a retro 80s synthwave interface inspired by GTA Vice City. Use a dark purple/black background with neon pink and cyan accents. The typography should feel like a retro vacation poster, using script or gradient fonts.",
    keywords: "vice city, synthwave, neon pink, retro 80s, miami vibe",
    bg: "bg-[#0e001a]",
    text: "text-[#00F0FF]",
    card: "bg-[#1A0526] border-2 border-[#FF00D4] shadow-[0_0_10px_rgba(255,0,212,0.4)] rounded-xl",
    button: "bg-gradient-to-r from-[#FF00D4] to-[#7000FF] text-white font-bold italic uppercase tracking-wider rounded-md border-none hover:shadow-[0_0_20px_rgba(255,0,212,0.6)]",
    buttonSec: "bg-transparent text-[#FF00D4] border-2 border-[#FF00D4] hover:bg-[#FF00D4]/20 rounded-md font-bold uppercase",
    input: "bg-[#1A0526] border-b-2 border-[#00F0FF] text-[#00F0FF] focus:border-[#FF00D4] rounded-t-md placeholder-[#00F0FF]/40",
    highlight: "text-[#FF00D4] drop-shadow-[0_0_5px_rgba(255,0,212,0.8)]",
    badge: "bg-gradient-to-r from-[#00F0FF] to-[#0088FF] text-black font-bold rounded-sm skew-x-[-10deg]",
    font: "font-sans",
  },

  pokemon: {
    name: "Gameboy (寶可夢)",
    desc: "復古掌機綠、點陣字體、懷舊邊框",
    prompt: "Design a retro Gameboy interface inspired by classic Pokemon. Use the iconic 4-color green palette (#0F380F, #306230, #8BAC0F, #9BBC0F). Elements should be pixelated with thick borders, resembling an 8-bit handheld screen.",
    keywords: "gameboy, pokemon red blue, 8-bit, retro green, pixel art, handheld",
    bg: "bg-[#8BAC0F]",
    text: "text-[#0F380F]",
    card: "bg-[#9BBC0F] border-4 border-[#0F380F] rounded-sm shadow-[4px_4px_0_rgba(15,56,15,0.4)]",
    button: "bg-[#306230] text-[#9BBC0F] border-2 border-[#0F380F] hover:bg-[#0F380F] font-bold uppercase rounded-sm shadow-[2px_2px_0_#0F380F]",
    buttonSec: "bg-[#9BBC0F] text-[#0F380F] border-2 border-[#0F380F] hover:bg-[#8BAC0F] rounded-sm",
    input: "bg-[#9BBC0F] border-b-4 border-[#0F380F] text-[#0F380F] placeholder-[#306230] focus:bg-[#8BAC0F] rounded-none px-2",
    highlight: "underline decoration-4 decoration-[#0F380F]",
    badge: "bg-[#0F380F] text-[#9BBC0F] rounded-full px-2 py-0 border border-[#9BBC0F]",
    font: "font-mono",
  },

  elden: {
    name: "Elden Ring (法環)",
    desc: "暗金、優雅襯線體、魂系美學",
    prompt: "Create a dark fantasy interface inspired by Elden Ring. Use a deep, dark texture background with muted gold (#Cfb67e) accents. Typography should be elegant serif fonts. UI elements should feel ancient, minimal, and ethereal.",
    keywords: "elden ring, dark fantasy, gold serif, minimal, ethereal, souls-like",
    bg: "bg-[#131313]",
    text: "text-[#Cfb67e]",
    card: "bg-[#1c1c1c] border border-[#4a4a4a] shadow-2xl rounded-sm opacity-95",
    button: "bg-[#2a2a2a] text-[#Cfb67e] border border-[#5a5a5a] hover:border-[#Cfb67e] hover:bg-[#333] font-serif tracking-widest uppercase text-sm rounded-sm transition-all duration-500",
    buttonSec: "bg-transparent text-[#888] hover:text-[#Cfb67e] border border-transparent hover:border-[#444] rounded-sm font-serif uppercase text-sm",
    input: "bg-[#0a0a0a] border-b border-[#444] text-[#Cfb67e] focus:border-[#Cfb67e] placeholder-[#444] rounded-none font-serif",
    highlight: "text-[#FFD700] drop-shadow-[0_0_8px_rgba(255,215,0,0.3)]",
    badge: "bg-[#2a2a2a] text-[#Cfb67e] border border-[#444] rounded-none font-serif text-xs uppercase tracking-widest",
    font: "font-serif",
  },
} as const

export type StyleKey = keyof typeof styles
